name: Continuous Deployment Wisnu K

on:
  push:
    branches:
      - main

jobs:
  connection-server:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Authentication
        uses: actions/checkout@v3
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
      # RUN already local triggers
  build-frontend:
    runs-on: self-hosted
    needs: connection-server
    steps:
      - uses: actions/checkout@v3

      - name: Authentication
        uses: actions/checkout@v3
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
      # RUN already local triggers
      - run: |

          cd /root/web/private-nu/FE-Skripsi
          git reset --hard
          git pull origin main
          sudo docker compose -f docker-compose-prod.yml up --build --force-recreate --no-deps -d
